package com.citihive.payvote.entity;

/**
 * @author Sreekanth Varidhireddy
 * Sep 21, 2023
 */
import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import jakarta.persistence.CascadeType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.OneToOne;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;


@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "voter")
public class Voter {
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String voterID;

	@DynamoDBAttribute
	private String voterFirstname;
	@DynamoDBAttribute
	private String voterLastname;

	@DynamoDBAttribute
	private String voterTitle;

	@DynamoDBAttribute
	private String voterEmail;

	@DynamoDBAttribute
	private Boolean isUSCitizen;

	@DynamoDBAttribute
	private String address;

	@DynamoDBAttribute
	private String unit;

	@DynamoDBAttribute
	private String city;

	@DynamoDBAttribute
	private String state;

	@DynamoDBAttribute
	private String zipcode;

	@DynamoDBAttribute
	private Boolean hasID;

	@DynamoDBAttribute
	private Date dob;

	@DynamoDBAttribute
	private String phone1;

	@DynamoDBAttribute
	private String phone2;

	@DynamoDBAttribute
	@OneToOne(mappedBy="voter",cascade = CascadeType.ALL)
	private RegistrationStatus registrationStatus;

	/**
	 * @return the voterID
	 */
	public String getVoterID() {
		return voterID;
	}

	/**
	 * @param voterID the voterID to set
	 */
	public void setVoterID(String voterID) {
		this.voterID = voterID;
	}

	/**
	 * @return the voterFirstname
	 */
	public String getVoterFirstname() {
		return voterFirstname;
	}

	/**
	 * @param voterFirstname the voterFirstname to set
	 */
	public void setVoterFirstname(String voterFirstname) {
		this.voterFirstname = voterFirstname;
	}

	/**
	 * @return the voterLastname
	 */
	public String getVoterLastname() {
		return voterLastname;
	}

	/**
	 * @param voterLastname the voterLastname to set
	 */
	public void setVoterLastname(String voterLastname) {
		this.voterLastname = voterLastname;
	}

	/**
	 * @return the voterTitle
	 */
	public String getVoterTitle() {
		return voterTitle;
	}

	/**
	 * @param voterTitle the voterTitle to set
	 */
	public void setVoterTitle(String voterTitle) {
		this.voterTitle = voterTitle;
	}

	/**
	 * @return the voterEmail
	 */
	public String getVoterEmail() {
		return voterEmail;
	}

	/**
	 * @param voterEmail the voterEmail to set
	 */
	public void setVoterEmail(String voterEmail) {
		this.voterEmail = voterEmail;
	}

	/**
	 * @return the isUSCitizen
	 */
	public Boolean getIsUSCitizen() {
		return isUSCitizen;
	}

	/**
	 * @param isUSCitizen the isUSCitizen to set
	 */
	public void setIsUSCitizen(Boolean isUSCitizen) {
		this.isUSCitizen = isUSCitizen;
	}

	/**
	 * @return the address
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * @param address the address to set
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * @return the unit
	 */
	public String getUnit() {
		return unit;
	}

	/**
	 * @param unit the unit to set
	 */
	public void setUnit(String unit) {
		this.unit = unit;
	}

	/**
	 * @return the city
	 */
	public String getCity() {
		return city;
	}

	/**
	 * @param city the city to set
	 */
	public void setCity(String city) {
		this.city = city;
	}

	/**
	 * @return the state
	 */
	public String getState() {
		return state;
	}

	/**
	 * @param state the state to set
	 */
	public void setState(String state) {
		this.state = state;
	}

	/**
	 * @return the zipcode
	 */
	public String getZipcode() {
		return zipcode;
	}

	/**
	 * @param zipcode the zipcode to set
	 */
	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	/**
	 * @return the hasID
	 */
	public Boolean getHasID() {
		return hasID;
	}

	/**
	 * @param hasID the hasID to set
	 */
	public void setHasID(Boolean hasID) {
		this.hasID = hasID;
	}

	/**
	 * @return the dob
	 */
	public Date getDob() {
		return dob;
	}

	/**
	 * @param dob the dob to set
	 */
	public void setDob(Date dob) {
		this.dob = dob;
	}

	/**
	 * @return the phone1
	 */
	public String getPhone1() {
		return phone1;
	}

	/**
	 * @param phone1 the phone1 to set
	 */
	public void setPhone1(String phone1) {
		this.phone1 = phone1;
	}

	/**
	 * @return the phone2
	 */
	public String getPhone2() {
		return phone2;
	}

	/**
	 * @param phone2 the phone2 to set
	 */
	public void setPhone2(String phone2) {
		this.phone2 = phone2;
	}

	/**
	 * @return the registrationStatus
	 */
	public RegistrationStatus getRegistrationStatus() {
		return registrationStatus;
	}

	/**
	 * @param registrationStatus the registrationStatus to set
	 */
	public void setRegistrationStatus(RegistrationStatus registrationStatus) {
		this.registrationStatus = registrationStatus;
	}

}